# Generated by Django 4.2.9 on 2024-02-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150000)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='null', upload_to='static/events')),
                ('eventUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='memberProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileType', models.CharField(choices=[('Github', 'Github'), ('Linkedin', 'Linkedin')], default='Profile', max_length=1500)),
                ('profileUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15000)),
                ('about', models.TextField()),
                ('position', models.CharField(max_length=15000)),
                ('memberType', models.CharField(choices=[('Team', 'Team'), ('Contributor', 'Contributor')], default='Team', max_length=100)),
                ('profile', models.ManyToManyField(to='home.memberprofiles')),
            ],
        ),
    ]
