# Generated by Django 4.2.9 on 2024-02-03 11:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15000)),
                ('about', models.TextField()),
                ('position', models.CharField(max_length=15000)),
                ('memberType', multiselectfield.db.fields.MultiSelectField(choices=[('team', 'team'), ('contributor', 'contributor')], max_length=100)),
            ],
        ),
    ]
