# Generated by Django 4.2.9 on 2024-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberType',
            field=models.CharField(choices=[('TEAM', 'team'), ('CONTIRBUTOR', 'contributor')], default='TEAM', max_length=100),
        ),
    ]
