# Generated by Django 4.2.9 on 2024-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_member_membertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150000)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='null', upload_to='static/events')),
                ('eventUrl', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='memberType',
            field=models.CharField(choices=[('Team', 'Team'), ('Contributor', 'Contributor')], default='Team', max_length=100),
        ),
    ]
