# Generated by Django 4.2.9 on 2024-02-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_memberprofiles_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
    ]
