# Generated by Django 4.2.9 on 2024-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_alter_member_membertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='temp',
            field=models.JSONField(default=''),
        ),
    ]
