# Generated by Django 4.2.9 on 2024-02-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_member_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='memberProfiles',
            new_name='memberProfile',
        ),
    ]
