# Generated by Django 4.2.9 on 2024-02-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_memberprofiles_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to='home.member'),
        ),
    ]
