# Generated by Django 4.2.9 on 2024-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='temp',
            field=models.JSONField(default=dict),
        ),
    ]
