# Generated by Django 4.2.9 on 2024-02-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_event_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='temp',
        ),
    ]
