# Generated by Django 4.2.9 on 2024-02-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_description_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_Url',
            field=models.CharField(max_length=1500),
        ),
    ]
