# Generated by Django 4.2.9 on 2024-02-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_Url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.CharField(max_length=150000),
        ),
    ]
