# Generated by Django 4.2.9 on 2024-02-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_eventimages_remove_event_image_event_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event_Date_Time',
            new_name='eventDateTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event_Url',
            new_name='eventUrl',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Image_Url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_Type',
            new_name='memberType',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Position',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Images',
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventImagesField', to='home.event'),
        ),
    ]
