# Generated by Django 4.2.9 on 2024-02-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_eventimages_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=15000)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
