# Generated by Django 4.2.9 on 2024-02-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_blog_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventImage', to='home.event'),
        ),
    ]
