# Generated by Django 4.2.9 on 2024-02-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_eventimages_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventImages', to='home.event')),
            ],
        ),
        migrations.DeleteModel(
            name='eventImages',
        ),
    ]
