# Generated by Django 4.2.9 on 2024-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_eventimage_delete_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
