# Generated by Django 4.2.9 on 2024-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventDateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
