# Generated by Django 4.2.9 on 2024-02-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_event_eventdatetime_event_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDate',
            new_name='date',
        ),
    ]
