# Generated by Django 4.2.9 on 2024-02-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_blog_id_alter_event_id_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventImages', to='home.event'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='home.member'),
        ),
    ]
