# Generated by Django 4.2.9 on 2024-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_blog_id_alter_event_id_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='profileType',
            field=models.CharField(choices=[('Github', 'Github'), ('Linkedin', 'Linkedin'), ('Medium', 'Medium'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Portfolio', 'Portfolio')], default='Profile', max_length=1500),
        ),
    ]
